# Generated by Django 4.0.4 on 2022-05-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCompleto', models.CharField(max_length=256)),
                ('dataNascimento', models.DateField()),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
    ]
