# Generated by Django 4.0.4 on 2022-05-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CursosDisponiveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=150)),
                ('professor', models.CharField(max_length=50)),
                ('contato_professor', models.CharField(max_length=30)),
                ('data_curso', models.DateField()),
                ('tempo_duracao', models.TimeField()),
            ],
        ),
    ]
