# Generated by Django 4.0.4 on 2022-05-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_remove_cursosdisponiveis_tempo_duracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosdisponiveis',
            name='data_curso',
            field=models.DateTimeField(),
        ),
    ]
