# Generated by Django 4.0.4 on 2022-05-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_cursosdisponiveis_data_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosdisponiveis',
            name='contato_professor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
